### ISSUE TITLE
How to handle navigating to the same page

### ISSUE THREAD

**Issue by carlosagsmendes** [Profiscience/ko-component-router#57] opened 2016-06-03 22:52 UTC
Hi @caseyWebb, when navigating to the same route (e.g., users/1, users/2, etc, for a users/:userId route) the respective component is not reloaded. 

As such, currently, I'm subscribing to the `ctx.params.userId` Observable to detect the navigation change. Then I have to handle the disposal cycle and call the `dispose()`method on the KO component, reload the data, etc.

I was wondering if it wouldn't be possible to call the component's `dispose()` automatically and instantiate a new viewModel with the new params.

Thanks

**Comment by caseyWebb** [comment] 2016-06-03 23:51
This is done by design with the intent that `ctx.params.userId` would be accessed in a computed. Would it be possible to refactor your viewmodel in a way that you don't have to dispose and re-construct for changed params?

**Comment by carlosagsmendes** [comment] 2016-06-04 22:09
In all my components for editing content, I use several items that need to be disposed. Some examples:

### Computed to track if the model is valid

```
this.isValid = ko.computed(function () {
            let isValid = true;
            this.validatableObservables().forEach(vo => {
                if (!vo.isValid()) {
                    isValid = false;
                    return;
                }
            });
            return isValid;

        }, this, {
            deferEvaluation: true
        });
```

### Computed to know if there are changes

```
this.hasChanges = ko.computed(function () {
            let hasChanges = false;
            this.editableObservables().forEach(vo => {
                if (vo.hasChanges()) {
                    hasChanges = true;
                    return;
                }
            });
            return hasChanges;
        }, this, {
            deferEvaluation: true
        });
```

I need to further understand if I can convert these computeds into pureComputeds (to avoid having to dispose them). Nevertheless, in some viewmodels I also use subscriptions and make use of some timers with setInterval. 

KO Components call the dispose() method of their viewModel when they are unloaded automatically, so I have a nice hook to clean up. 

My problem is only when handling navigation to the same "page", when the same components aren't reloaded (and therefore the dispose() method is not called).

Even though I can manage this manually when I need to reload data for a component (e.g., navigating from users/1 to users/2) I think it is very easy to miss it.

Do you have any suggestion on how to handle it?

Also, I was wondering if you would consider adding some optional lifecycle hooks that we can attach to viewModels (this is based on Aurelia.io):

**activate(params, routeConfig, navigationInstruction)** - _Implement this hook if you want to perform custom logic just before your view-model is displayed. You can optionally return a promise to tell the router to wait to bind and attach the view until after you finish your work._ This would be helpful to know when the route has changed even if we are on the same page (e.g., navigating from users/1 to users/2)

**canDeactivate()** - _Implement this hook if you want to control whether or not the router can navigate away from your view-model when moving to a new route. Return a boolean value, a promise for a boolean value, or a navigation command._ This would be useful for example to have the chance to ask the user if he wants to proceed with the navigation if he has unsaved changes

**deactivate()** - _Implement this hook if you want to perform custom logic when your view-model is being navigated away from. You can optionally return a promise to tell the router to wait until after your finish your work._ This would be the hook for cleaning up

If so, we could further discuss this and I can contribute with a PR.

Thank you for your help

**Comment by caseyWebb** [comment] 2016-06-04 23:54
Typically I recommend structuring your viewmodels is a way that you only need to manage one disposal and all the data ripples down from there, as such.

``` javascript
class ViewModel {
  constructor(ctx) {
    this.ready = ko.observable(false)

    this._sub = ctx.params.id.subscribe((id) => {
      $.get('/api/user', { id })
       .then((user) => {
         ko.mapping({ user }, this)

         if (!this.ready()) {
           this.initValidation()
           this.ready(true)
         }
       })
    })
  }

  initValidation() {
    const validatable = [
      this.name.extend({ required: true }),
      this.email.extend({ required: true })
    ]

    this.isValid = ko.pureComputed(() => {
      let v = true
      validatable.forEach((p) => {
        if (!p.isValid()) {
          v = false
        }
      })
      return v
    })
  }

  dispose() {
    this._sub.dispose()
  }
}
```

I can agree that there is room in the api to tell the router that certain components should reload on param change, though. I prefer this way as there is way less jarring on the page — it avoids the blank in between state (`this.ready() === false`).

**Comment by caseyWebb** [comment] 2016-06-05 00:17
Regarding the lifecycle callbacks, the only one I think the first would be better implemented in a component loader, but there is a need for a cancelable, async unload callback. I've been floating around the idea of something like this for a while...

``` javascript
ctx.addDisposeCallback(() => somePromiseReturningFunc)
// promise.reject, cancel navigation 
// promise.resolve, continue navigation

ctx.addDisposeCallback((done) => {
  done(false) // cancel navigation
  done() // continue navigation
})

ctx.addDisposeCallback(doWorkSync)
```

**Comment by carlosagsmendes** [comment] 2016-06-06 11:19
Thanks for the code @caseyWebb.

Could you provide further details on the following:

_I prefer this way as there is way less jarring on the page — it avoids the blank in between state (this.ready() === false)._

Do you use the ready() to decide when to render (like in a if binding in the html template)?

Also, what would be the case for cancelling during the disposal?

Cheers

**Comment by caseyWebb** [comment] 2016-06-06 13:28
#### this.ready()

Using `this.ready` and wrapping the template in `<!-- ko if: ready --><!-- /ko -->` is how I normally do things. The UX on that is to react immediately to clicks on the UI and then let the page manage it's own rendering. In this case, subbing to the params or using them in a computed has worked well so far. IMO this is more "app like" behavior, but it's extremely tedious to make it really look good because you have to define min and max sizes for pretty much everything and add loading icons/animations.

With that being said, from a coding standpoint it's less than ideal. Thinking out loud here... it wouldn't be difficult to implement a component loader that returns a promised viewmodel and resolves when the viewmodel has all the data. In this case you would need the router to reload on every call. This would give a clean API, but the downside is that the page will be blank while the loader is resolving the data (I think — I've not confirmed this is how loaders work). If a succinct way to achieve this API could be found that keeps the current component in place until the new one has it's data I'd be all for it.

#### this.addNavigateCallback()

NavigateCallback is a better name for this than DisposeCallback, but alas. I don't know Aurelia — but with the hooks you described, I would assume it would provide the same functionality as `canDeactivate` and `deactivate`, but in one function.

``` javascript
ctx.addNavigateCallback(() => {
  if (this.saving) {
    return false
  }

  return this.doAsyncCleanup()
})
```

Assuming `this.doAsyncCleanup()` returned a promise that resolved a value !== false.

**Comment by carlosagsmendes** [comment] 2016-06-06 13:47
Thanks for the clarification. 

The addNavigateCallback would be a great addition.

I do follow the same approach that you've described with _this.ready()_ and works fine but as you've said is less than ideal.  The loader approach would be very nice but I don't know how could we keep the current component in place seems hard. Do you have any idea on how to achieve that?

**Comment by caseyWebb** [comment] 2016-06-07 13:33
Turns out it would be a lot more difficult than I thought to implement `activate` in a component loader the way I had originally thought. It was promising, but ultimately fruitless.

https://jsfiddle.net/hejtL5cg/2/

**Comment by carlosagsmendes** [comment] 2016-06-07 14:47
I was reading the [documentation ](http://knockoutjs.com/documentation/component-loaders.html) and they mention that:

_To supply a createViewModel function, call callback(yourCreateViewModelFunction). The createViewModel function must accept parameters (params, componentInfo) and **must synchronously return a new viewmodel instance** each time it is called._

Therefore it is not possible to use promises in the create view model factory, right?

**Comment by caseyWebb** [comment] 2016-06-07 15:32
That is correct, you can't use them inside. I was trying to hack around that by doing the async work in the loader, but the results of this loader are cached so if there are more than 1 of that component on the page, they share the same vm instance. If there was an option to not cache this loader then it would would probably work, but alas there is no such option.

**Comment by carlosagsmendes** [comment] 2016-06-08 11:51
Could you check [this example](https://jsfiddle.net/carlosagsmendes/hejtL5cg/39/)?

Since the createViewModel needs to return immediately, we would have to move the initialization logic to a method that would return a promise (**activate** in this case).

**Closed as completed** 2016-06-14 03:20 UTC
